### ISSUE TITLE
请教api.rlair.live返回的是一个什么数据形态的json呀

### ISSUE THREAD

**Issue by todeem** [flyce/rlair.live#1]
var result = fetch("https://api.rlair.live/" + url).then(function (data) {
  3 |         return data.json();
返回的是一个什么数据形态的json呀，可以提供一下 学习吗？

![QQ图片20230614151029](ht
![image](https://github.com/flyce/rlair.live/assets/2862136/c969b0f4-c78b-4a40-988e-e33b2e8b24d3)
tps://github.com/flyce/rlair.live/assets/2862136/fe2a3691-66fa-4362-b7ec-10e5ff2e38ff)

**Comment by flyce** [comment]
已经开源了
参考这个https://github.com/flyce/rlairgo
```
{
     "title": "坚果Pro",
     "imageUrl": "http://192.168.123.107:3000/image.jpg",
     "src": "http://192.168.123.107:3000/demo.mp4",
     "introduction": "坚果 Pro，是锤子科技在2017年5月9日晚在深圳正式发布的旗下的第五款新机。全玻璃面板与金属中框，采用了双摄像头，拥有6.98mm的厚度，158g的重量，拥有红色和黑色两种常规配色，同时，加入了细红线版本。",
     "source": "smartisan"
 }
```
